FROM openjdk:8-jre-alpine
COPY ./target/UserMicroservice-0.0.1-SNAPSHOT.jar /usr/src/UserMicroservice/
WORKDIR /usr/src/UserMicroservice
EXPOSE 8091
CMD ["java", "-jar", "UserMicroservice-0.0.1-SNAPSHOT.jar"]