FROM openjdk:8-jre-alpine
COPY ./target/eureka-service-0.0.1-SNAPSHOT.jar /usr/src/eureka-service/
WORKDIR /usr/src/eureka-service
EXPOSE 8090
CMD ["java", "-jar", "eureka-service-0.0.1-SNAPSHOT.jar"]