version: '2.2'
services:
  eurekaservice:
    container_name: eurekaservice
    build: ./eureka-service
    image: eurekaservice:latest
    ports:
      - 8090:8090
    networks:
      - study-planner-network
  gatway:
    build: ./zuul-service
    image: zuul-service:latest
    depends_on:
      - eurekaservice
    ports:
      - 8080:8080
    environment:
      - SPRING_APPLICATION_NAME=ZUUL-SERVICE
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaservice:8090/eureka
    networks:
      - study-planner-network
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - study-planner-network   
  taskmicroservice:
    build: ./TaskMicroservice
    image: taskmicroservice:latest
    depends_on: 
      - eurekaservice
      - rabbitmq
    ports: 
      - 8092:8092
    environment:
      - SPRING_APPLICATION_NAME=TASKMICROSERVICE
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaservice:8090/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - study-planner-network
  activitymicroservice: 
    build: ./ActivityMicroservice
    image: activitymicroservice:latest
    depends_on: 
      - eurekaservice
      - rabbitmq
    ports: 
      - 8094:8094
    environment:
      - SPRING_APPLICATION_NAME=ACTIVITYMICROSERVICE
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaservice:8090/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - study-planner-network
  coursemicroservice: 
    build: ./CourseMicroservice
    image: coursemicroservice:latest
    depends_on: 
      - eurekaservice
      - rabbitmq
    ports: 
      - 8093:8093
    environment:
      - SPRING_APPLICATION_NAME=COURSEMICROSERVICE
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaservice:8090/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - study-planner-network
  usermicroservice:
    build: ./UserMicroservice
    image: usermicroservice:latest
    depends_on: 
      - eurekaservice
      - rabbitmq
    ports: 
      - 8091:8091
    environment:
      - SPRING_APPLICATION_NAME=USERMICROSERVICE
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaservice:8090/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - study-planner-network
networks: 
  study-planner-network:
    driver: bridge