FROM openjdk:8-jre-alpine
COPY ./target/CourseMicroservice-0.0.1-SNAPSHOT.jar /usr/src/CourseMicroservice/
WORKDIR /usr/src/CourseMicroservice
EXPOSE 8093
CMD ["java", "-jar", "CourseMicroservice-0.0.1-SNAPSHOT.jar"]